Document: babel
Title: Debian babel Manual
Author: <insert document author here>
Abstract: This manual describes what babel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/babel/babel.sgml.gz

Format: postscript
Files: /usr/share/doc/babel/babel.ps.gz

Format: text
Files: /usr/share/doc/babel/babel.text.gz

Format: HTML
Index: /usr/share/doc/babel/html/index.html
Files: /usr/share/doc/babel/html/*.html
